drop table if exists hits , app_dict , uri_dict;

create table if not exists app_dict (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app_name varchar(127) NOT NULL,
    constraint pk_app primary key (id)
);
create unique index if not exists APP_DICT_ID_UINDEX on app_dict (id);
create unique index if not exists APP_DICT_APP_NAME_UINDEX on app_dict (app_name);

create table if not exists uri_dict (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uri_name varchar(255) NOT NULL,
    constraint pk_uri primary key (id)
);
create unique index if not exists URI_DICT_ID_UINDEX on uri_dict (id);
create unique index if not exists URI_DICT_APP_NAME_UINDEX on uri_dict (uri_name);

create table if not exists hits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app_id BIGINT NOT NULL REFERENCES app_dict(id),
    uri_id BIGINT NOT NULL REFERENCES uri_dict(id),
    ip varchar(31) NOT NULL,
    "timestamp" timestamp without time zone not null,
    constraint pk_hits primary key (id)
);

